//package model;
//
//public class calzedoniaModel {
//
//
//    public LoginRegistrationManager loginRegistrationManager;
//    public UtilityManager utilityManager;
//    public InitManager initManager;
//    public UserManager userManager;
//    public AddressBookManager addressBookManager;
//    public ItemManager itemManager;
//    public CartManager cartManager;
//    public OrderManager orderManager;
//    public WishlistManager wishlistManager;


//    public void setManager() {
//        try {
//
//            ComponentManager componentManager = new ComponentManager();
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class ComponentManager is null", componentManager);
//
//            loginRegistrationManager = new LoginRegistrationManager();
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class LoginRegistrationManager is null", loginRegistrationManager);
//
//            utilityManager = new UtilityManager();
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class UtilityManager is null", utilityManager);

//            initManager = new InitManager();
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class InitManager is null", initManager);
//
//            userManager = new UserManager(componentManager, utilityManager, loginRegistrationManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class UserManager is null", userManager);
//
//            addressBookManager = new AddressBookManager(componentManager, utilityManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class AddressBook Manager is null", addressBookManager);
//
//            cartManager = new CartManager(componentManager, utilityManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class Cart Manager is null", cartManager);
//
//            itemManager = new ItemManager(componentManager, utilityManager, cartManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class ItemManager is null", itemManager);
//
//
//            wishlistManager = new WishlistManager(componentManager, utilityManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class Wishlist Manager is null", wishlistManager);
//
//            orderManager = new OrderManager(componentManager, cartManager, utilityManager);
//            assertNotNull("An error occurred during test starting, it could be generated by a server error. \n Class Order Manager is null", orderManager);

//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//}
